# Auto-Merge Workflow Template
#
# This workflow automatically merges PRs when:
# - All required CI checks pass
# - PR has auto-merge label
# - PR has no blocking labels
# - No merge conflicts
#
# Copy this to .github/workflows/auto-merge.yml

name: Auto-Merge
on:
  # Run when check suites complete
  check_suite:
    types: [completed]
  # Run when PRs are labeled
  pull_request:
    types: [labeled, synchronize]
  # Run when workflow runs complete
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types: [completed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request || github.event.check_suite || github.event.workflow_run
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Auto-merge eligible PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            // Configuration
            const autoMergeLabels = ['auto-merge', 'ready-to-merge'];
            const blockedLabels = ['do-not-merge', 'wip', 'blocked'];
            const mergeMethod = 'squash';
            const deleteBranch = true;
            
            // Get open PRs
            const { data: prs } = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open'
            });
            
            for (const pr of prs) {
              // Check for auto-merge label
              const hasAutoMergeLabel = pr.labels.some(l => 
                autoMergeLabels.includes(l.name)
              );
              if (!hasAutoMergeLabel) {
                console.log(`PR #${pr.number}: No auto-merge label, skipping`);
                continue;
              }
              
              // Check for blocked labels
              const hasBlockedLabel = pr.labels.some(l => 
                blockedLabels.includes(l.name)
              );
              if (hasBlockedLabel) {
                console.log(`PR #${pr.number}: Has blocking label, skipping`);
                continue;
              }
              
              // Get PR details for mergeable status
              const { data: prDetails } = await github.rest.pulls.get({
                owner,
                repo,
                pull_number: pr.number
              });
              
              if (!prDetails.mergeable) {
                console.log(`PR #${pr.number}: Not mergeable (conflicts?), skipping`);
                continue;
              }
              
              // Check CI status
              const { data: checkRuns } = await github.rest.checks.listForRef({
                owner,
                repo,
                ref: pr.head.sha
              });
              
              const allChecksPass = checkRuns.check_runs.every(check => 
                check.conclusion === 'success' || 
                check.conclusion === 'skipped' || 
                check.conclusion === 'neutral'
              );
              
              const hasRunningChecks = checkRuns.check_runs.some(check => 
                check.status === 'in_progress' || check.status === 'queued'
              );
              
              if (hasRunningChecks) {
                console.log(`PR #${pr.number}: CI still running, skipping`);
                continue;
              }
              
              if (!allChecksPass) {
                console.log(`PR #${pr.number}: CI checks failed, skipping`);
                continue;
              }
              
              // All checks pass - merge!
              console.log(`PR #${pr.number}: Merging...`);
              try {
                await github.rest.pulls.merge({
                  owner,
                  repo,
                  pull_number: pr.number,
                  merge_method: mergeMethod
                });
                console.log(`PR #${pr.number}: Merged successfully!`);
                
                // Delete branch if configured
                if (deleteBranch) {
                  try {
                    await github.rest.git.deleteRef({
                      owner,
                      repo,
                      ref: `heads/${pr.head.ref}`
                    });
                    console.log(`PR #${pr.number}: Branch deleted`);
                  } catch (e) {
                    console.log(`PR #${pr.number}: Could not delete branch: ${e.message}`);
                  }
                }
              } catch (error) {
                console.log(`PR #${pr.number}: Merge failed: ${error.message}`);
              }
            }
